"""
UNREEL V3 – Regie Engine (Multi-Provider)
Uses Claude Fable 5, Gemini 3.1 Pro, or DeepSeek V4 Pro as the creative director
to plan millisecond-precise edits based on audio/video analysis metadata.
Generates structured edit plans (Schnittlisten) with automatic provider fallback.

Usage:
    from analyzer.regie_engine import generate_edit_plan, verify_edit_plan
    plan = generate_edit_plan(analysis_data, preset="highlight", duration=60)

    # Explicit provider:
    plan = generate_edit_plan(data, provider="gemini")
    plan = generate_edit_plan(data, provider="deepseek")
    plan = generate_edit_plan(data, provider="claude")

CLI:
    python -m analyzer.regie_engine analysis.json --provider gemini --preset highlight
"""

import importlib.util
import json
import logging
import os
import time
from abc import ABC, abstractmethod
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional, Protocol

from analyzer.local_regie_provider import LocalMLXProvider

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration (loaded from config module / .env)
# ---------------------------------------------------------------------------

from config import (
    REGIE_PROVIDER,
    REGIE_PROVIDER_FALLBACK_ORDER,
    ANTHROPIC_API_KEY,
    CLAUDE_MODEL,
    GEMINI_API_KEY,
    GEMINI_MODEL,
    DEEPSEEK_API_KEY,
    DEEPSEEK_MODEL,
    DEEPSEEK_BASE_URL,
)

# ---------------------------------------------------------------------------
# SDK availability helper
# ---------------------------------------------------------------------------

def _sdk_installed(module_name: str) -> bool:
    """True if the given SDK module can be imported (without importing it)."""
    return importlib.util.find_spec(module_name) is not None


# ---------------------------------------------------------------------------
# Data classes (shared across all providers)
# ---------------------------------------------------------------------------

@dataclass
class EditClip:
    """A single clip in the edit plan."""
    video: str
    start: float
    end: float
    transition: str
    reason: str
    crop: str = "9:16"
    lut: str = "underground_dark"
    vfx: str = "none"
    slow_mo: bool = False
    slow_mo_factor: float = 1.0
    phase: str = ""  # Story phase for pov_story preset: "before" | "during" | "after"

    def to_dict(self) -> dict:
        return {
            "video": self.video,
            "start": round(self.start, 3),
            "end": round(self.end, 3),
            "duration": round(self.end - self.start, 3),
            "transition": self.transition,
            "reason": self.reason,
            "crop": self.crop,
            "lut": self.lut,
            "vfx": self.vfx,
            "slow_mo": self.slow_mo,
            "slow_mo_factor": self.slow_mo_factor,
            "phase": self.phase,
        }

    @property
    def duration(self) -> float:
        return self.end - self.start


@dataclass
class EditPlan:
    """Complete edit plan generated by AI."""
    clips: list[EditClip]
    narrative: str
    total_duration: float
    target_bpm: float = 0.0
    style: str = "highlight"
    hook_text: str = ""           # Anti-advice hook line (pov_story preset, first ~3s)
    provider_used: str = ""       # Which AI generated this plan
    model_used: str = ""          # Exact model identifier
    generation_time_s: float = 0.0

    def to_dict(self) -> dict:
        return {
            "clips": [c.to_dict() for c in self.clips],
            "narrative": self.narrative,
            "hook_text": self.hook_text,
            "total_duration": round(self.total_duration, 3),
            "target_bpm": self.target_bpm,
            "style": self.style,
            "clip_count": len(self.clips),
            "provider_used": self.provider_used,
            "model_used": self.model_used,
            "generation_time_s": round(self.generation_time_s, 2),
        }

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, indent=2, ensure_ascii=False)
        logger.info(f"Edit plan saved to {path}")

    def to_ffmpeg_commands(self, output_dir: Path = Path("output")) -> list[str]:
        """Convert the edit plan to FFmpeg command strings for execution."""
        commands = []
        for i, clip in enumerate(self.clips):
            vf_parts = []

            if clip.crop == "9:16":
                vf_parts.append("crop=ih*9/16:ih,scale=1080:1920")
            elif clip.crop == "16:9":
                vf_parts.append("scale=1920:1080")

            if clip.lut and clip.lut != "none":
                vf_parts.append(f"lut3d=luts/{clip.lut}.cube")

            if clip.slow_mo and clip.slow_mo_factor > 1.0:
                vf_parts.insert(0, f"setpts=PTS*{clip.slow_mo_factor}")

            # Beat-reactive VFX (applied at start of clip)
            if clip.vfx == "flash":
                vf_parts.append("eq=brightness=1.5:enable='between(t,0,0.2)'")
            elif clip.vfx == "pump":
                vf_parts.append("zoompan=z='min(max(zoom,pzoom)+0.03,1.05)':d=1:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s=1080x1920:enable='between(t,0,0.3)'")

            vf = ",".join(vf_parts) if vf_parts else None

            output_name = f"snippet_{i + 1:03d}_{Path(clip.video).stem}.mp4"
            output_path = output_dir / output_name

            cmd_parts = [
                "ffmpeg", "-y",
                "-ss", f"{clip.start:.3f}",
                "-to", f"{clip.end:.3f}",
                "-i", clip.video,
            ]
            if vf:
                cmd_parts.extend(["-vf", vf])
            cmd_parts.extend([
                "-c:v", "libx264", "-preset", "fast", "-crf", "23",
                "-c:a", "aac", "-b:a", "128k",
                "-movflags", "+faststart",
                str(output_path),
            ])
            commands.append(" ".join(cmd_parts))

        return commands


# ---------------------------------------------------------------------------
# Provider Protocol
# ---------------------------------------------------------------------------

class RegieProvider(Protocol):
    """Interface that all AI providers must implement."""

    @property
    def name(self) -> str: ...

    @property
    def model_id(self) -> str: ...

    def is_available(self) -> bool: ...

    def call(
        self,
        system_prompt: str,
        user_data: str,
        temperature: float = 0.4,
        max_tokens: int = 8192,
    ) -> str: ...


# ---------------------------------------------------------------------------
# Provider: Claude Fable 5 (Anthropic)
# ---------------------------------------------------------------------------

class ClaudeProvider:
    """Anthropic Claude provider – Claude Fable 5."""

    def __init__(
        self,
        api_key: str = ANTHROPIC_API_KEY,
        model: str = CLAUDE_MODEL,
    ):
        self._api_key = api_key
        self._model = model

    @property
    def name(self) -> str:
        return "claude"

    @property
    def model_id(self) -> str:
        return self._model

    def is_available(self) -> bool:
        return bool(self._api_key) and _sdk_installed("anthropic")

    def call(
        self,
        system_prompt: str,
        user_data: str,
        temperature: float = 0.4,
        max_tokens: int = 8192,
    ) -> str:
        if not self._api_key:
            raise ValueError("ANTHROPIC_API_KEY not set")

        try:
            import anthropic
        except ImportError:
            raise ImportError("anthropic not installed. Run: pip install anthropic")

        client = anthropic.Anthropic(api_key=self._api_key)

        logger.info(f"  → Calling {self._model} (Anthropic)...")

        params = dict(
            model=self._model,
            max_tokens=max_tokens,
            system=system_prompt,
            messages=[{"role": "user", "content": user_data}],
            temperature=temperature,
        )
        try:
            response = client.messages.create(**params)
        except anthropic.BadRequestError as exc:
            # Newer models (e.g. Fable 5) reject `temperature`; retry without it.
            if "temperature" in str(exc).lower():
                params.pop("temperature", None)
                response = client.messages.create(**params)
            else:
                raise

        # Fable 5 (and any model with extended thinking) returns thinking
        # blocks before the answer, so pick text blocks only — never content[0].
        text = "".join(
            block.text for block in response.content
            if getattr(block, "type", None) == "text"
        )
        return text


# ---------------------------------------------------------------------------
# Provider: Gemini 3.1 Pro (Google)
# ---------------------------------------------------------------------------

class GeminiProvider:
    """Google Gemini provider – Gemini 3.1 Pro."""

    def __init__(
        self,
        api_key: str = GEMINI_API_KEY,
        model: str = GEMINI_MODEL,
    ):
        self._api_key = api_key
        self._model = model

    @property
    def name(self) -> str:
        return "gemini"

    @property
    def model_id(self) -> str:
        return self._model

    def is_available(self) -> bool:
        return bool(self._api_key) and _sdk_installed("google.generativeai")

    def call(
        self,
        system_prompt: str,
        user_data: str,
        temperature: float = 0.4,
        max_tokens: int = 8192,
    ) -> str:
        if not self._api_key:
            raise ValueError("GEMINI_API_KEY not set")

        try:
            import google.generativeai as genai
        except ImportError:
            raise ImportError("google-generativeai not installed. Run: pip install google-generativeai")

        genai.configure(api_key=self._api_key)

        model = genai.GenerativeModel(
            model_name=self._model,
            system_instruction=system_prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=temperature,
                max_output_tokens=max_tokens,
                response_mime_type="application/json",  # Force JSON output
            ),
        )

        logger.info(f"  → Calling {self._model} (Google Gemini)...")

        response = model.generate_content(user_data)

        return response.text


# ---------------------------------------------------------------------------
# Provider: DeepSeek V4 Pro
# ---------------------------------------------------------------------------

class DeepSeekProvider:
    """DeepSeek provider – V4 Pro via OpenAI-compatible API."""

    def __init__(
        self,
        api_key: str = DEEPSEEK_API_KEY,
        model: str = DEEPSEEK_MODEL,
        base_url: str = DEEPSEEK_BASE_URL,
    ):
        self._api_key = api_key
        self._model = model
        self._base_url = base_url

    @property
    def name(self) -> str:
        return "deepseek"

    @property
    def model_id(self) -> str:
        return self._model

    def is_available(self) -> bool:
        return bool(self._api_key) and _sdk_installed("openai")

    def call(
        self,
        system_prompt: str,
        user_data: str,
        temperature: float = 0.4,
        max_tokens: int = 8192,
    ) -> str:
        if not self._api_key:
            raise ValueError("DEEPSEEK_API_KEY not set")

        try:
            from openai import OpenAI
        except ImportError:
            raise ImportError("openai not installed. Run: pip install openai")

        client = OpenAI(
            api_key=self._api_key,
            base_url=self._base_url,
        )

        logger.info(f"  → Calling {self._model} (DeepSeek)...")

        response = client.chat.completions.create(
            model=self._model,
            max_tokens=max_tokens,
            temperature=temperature,
            response_format={"type": "json_object"},  # Force JSON
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_data},
            ],
        )

        return response.choices[0].message.content


# ---------------------------------------------------------------------------
# Provider Registry & Resolution
# ---------------------------------------------------------------------------

def get_provider(provider_name: str = "") -> RegieProvider:
    """
    Instantiate a provider by name. Empty string uses REGIE_PROVIDER from config.
    Raises ValueError if the provider is not available (missing API key).
    """
    name = provider_name or REGIE_PROVIDER
    name = name.lower().strip()

    providers: dict[str, type] = {
        "claude": ClaudeProvider,
        "gemini": GeminiProvider,
        "deepseek": DeepSeekProvider,
        "local": LocalMLXProvider,
    }

    if name not in providers:
        raise ValueError(f"Unknown provider '{name}'. Choose from: {', '.join(providers)}")

    return providers[name]()


def resolve_provider(provider_name: str = "") -> RegieProvider:
    """
    Resolve the active provider. Handles "auto" mode by trying each provider
    in fallback order until one with a configured API key is found.
    """
    name = (provider_name or REGIE_PROVIDER).lower().strip()

    if name != "auto":
        provider = get_provider(name)
        if not provider.is_available():
            raise ValueError(
                f"Provider '{name}' is not available – "
                f"the required API key is not set in .env or environment."
            )
        return provider

    # Auto mode: try each provider in fallback order
    logger.info(f"Auto-selecting provider (fallback order: {' → '.join(REGIE_PROVIDER_FALLBACK_ORDER)})...")

    for candidate_name in REGIE_PROVIDER_FALLBACK_ORDER:
        try:
            provider = get_provider(candidate_name)
            if provider.is_available():
                logger.info(f"  ✓ Selected: {provider.name} ({provider.model_id})")
                return provider
            else:
                logger.debug(f"  ✗ {candidate_name}: API key not set")
        except Exception as e:
            logger.debug(f"  ✗ {candidate_name}: {e}")

    raise ValueError(
        "No AI provider available. Set at least one API key in .env:\n"
        "  ANTHROPIC_API_KEY=...  (Claude Fable 5)\n"
        "  GEMINI_API_KEY=...     (Gemini 3.1 Pro)\n"
        "  DEEPSEEK_API_KEY=...   (DeepSeek V4 Pro)\n"
        "Or set REGIE_PROVIDER=local to use the local model."
    )


def list_available_providers() -> list[dict]:
    """List all providers and their availability status."""
    result = []
    for name, cls in [("claude", ClaudeProvider), ("gemini", GeminiProvider), ("deepseek", DeepSeekProvider), ("local", LocalMLXProvider)]:
        provider = cls()
        result.append({
            "name": name,
            "model": provider.model_id,
            "available": provider.is_available(),
        })
    return result


# ---------------------------------------------------------------------------
# System prompt builder (shared across all providers)
# ---------------------------------------------------------------------------

_POV_STORY_SECTION = """
POV / "A DAY IN THE LIFE" STORY MODE (preset = pov_story) — this OVERRIDES the generic editing rules above.
This is a story-driven, POV vlog-style reel, NOT a beat-cut highlight montage. Build a mini narrative across
three phases of a gig:
  - "before": arriving, getting ready, soundcheck, backstage, nerves, walking to the booth (ARRIVAL / BACKSTAGE / DJ_SETUP)
  - "during": the actual set — mixing, the drop, the crowd reacting (CROWD_ENERGY / LIGHT_SHOW / DJ_SETUP)
  - "after": the comedown — last track, packing up, crowd leaving, the quiet after (PACKDOWN / BACKSTAGE / BREAKDOWN)

POV STORY RULES:
1. DO use ARRIVAL, PACKDOWN and BACKSTAGE clips here — they carry the "before" and "after" story. The generic "avoid BACKSTAGE" rule does NOT apply. ARRIVAL strongly signals "before"; PACKDOWN strongly signals "after".
2. Order clips chronologically as a narrative: before -> during -> after. Set each clip's "phase" field accordingly.
3. Cuts may be motivated by story beats, not only kicks/snares. Pacing: slower (before) -> peak (during) -> settle (after).
4. Establishing clips in "before"/"after" may run a bit longer (up to ~6s); keep the "during" phase punchy.
5. The FIRST clip is the HOOK (first ~3 seconds) and MUST stop the scroll.

ANTI-ADVICE HOOK (REQUIRED — put it in the top-level "hook_text" field):
Write ONE short, punchy on-screen text line for the first 3 seconds. It is "anti-advice": deliberately
contrarian / counterintuitive / provocative — the OPPOSITE of a polite tip. Bait the viewer by challenging
conventional DJ wisdom or undercutting expectations. Under ~60 characters, no hashtags, no emojis.
Match this energy (do NOT copy verbatim):
  - "stop practicing your transitions."
  - "nobody cares about your warm-up set."
  - "POV: ignored every DJ tip and still packed the floor"
  - "the crowd doesn't want your 'journey'."
Make the hook thematically connect to what actually happens in the chosen clips.
"""


_TARANTINO_SECTION = """
TARANTINO / PERSONALISED RETENTION-PIPELINE MODE (preset = tarantino) — this OVERRIDES the generic editing rules above.
This is a precision‑timed reel based on the four‑phase "Retention‑Pipeline" dramaturgy.
The reel is exactly 30 seconds long. The analysis data includes "music_analysis" with "drop_times",
where each entry is an object {"time": seconds, "intensity": 0..1}.
If a drop exists, the final drop time = drop_times[0].time (the "time" field of the FIRST entry) and
phase 4 (escalation) MUST start exactly at that time.
If no music_analysis is present, the default final drop time is 12.0s.

ABSOLUTE TIMELINE (each clip's "phase" field must be set accordingly):

1. "hook" (0.0s – 3.0s) — PATTERN INTERRUPT (BEAT-SYNC, 1/4 NOTES)
   START IN MEDIA RES. No intro, no warning – fire the most intense club shot instantly.
   EVERY kick drum = ONE cut. That is fast enough to show energy, but still readable.
   Content: deep red light, strobes, you at the decks, crowd going off (CROWD_ENERGY / LIGHT_SHOW).
   Clip duration: multiples of a 1/4 note at the track BPM (use subdivision_grid). 
   LUT: "underground_dark" or "neon_nights". VFX: "flash" on the hardest hit.

2. "flashback" (3.0s – 8.0s) — DOPAMIN RESET (HALF-TIME, 1/2 NOTES TO WHOLE BARS)
   HARD CONTRAST to the hook. Drop visual energy drastically. Use long, stoic, almost monochrome shots
   (train, walking, field, outdoor). Let clips breathe for 2 beats (1/2 note) or even 4 beats (one bar).
   The quiet images feel oppressive because the muffled bass (J‑cut lowpass) rumbles underneath.
   Content: ARRIVAL / BACKSTAGE / outdoor. Chronological backstory.
   Clip duration: "1/2_half" or "1/1_bar" values from subdivision_grid. NO fast cutting here.
   LUT: "tech_noir" (cold, monochrome, high-contrast). VFX: "none".

3. "buildup" (8.0s – 12.0s) — SNARE‑ROLL ACCELERATION (1/4 → 1/8 NOTES)
   The track rolls toward the drop. Mirror the tension with accelerating cut frequency.
   START with 1/4‑note cuts, and in the LAST TWO BARS before the drop switch to double‑time (1/8 notes).
   This is the visual "snare roll" – the rhythm tightens exactly as the music does.
   Content: branding shots – artist unapproachable: hands on mixer, adjusting glasses, looking into
   camera, back shots (DJ_SETUP). Cut them rhythmically, getting faster.
   LUT: "tech_noir". The LAST clip that transitions into Phase 4 → VFX: "glitch" (black‑frame stutter).

4. "escalation" (12.0s – 30.0s) — DOUBLE‑TIME MASSACRE (1/8 BASE + 1/16 GLITCHES)
   THE DROP. Bass hits, filter opens. Full 1/8‑note cutting as baseline.
   For absolute peaks (drops, strobes) insert ultra‑short 1/16‑note micro‑cuts (≈0.1s) – percussive
   visual glitches, not meant to be fully readable, just felt.
   Content: hands on XONE mixer, sweating crowd, strobes, chaos (CROWD_ENERGY / LIGHT_SHOW / DJ_SETUP).
   LUT: "underground_dark" / "neon_nights". VFX: "pump" on driving kicks, "flash" on hardest drops.

MUSIC DROP ALIGNMENT:
If music_analysis.drop_times is available, the "final drop" time = drop_times[0].time
(each drop_times entry is {"time": seconds, "intensity": 0..1}).
Phase 3 (buildup) ends at the later of 12.0s or (drop_time – 2.0s) – this ensures at least
two bars of buildup before the drop. Phase 4 (escalation) starts at drop_time and stretches
to 30.0s. If no drop_time, default drop = 12.0s.

DURATION MATH:
The reel is exactly 30.0s. The four phases occupy:
  hook:        0.0 –  3.0 = 3.0s  (fixed)
  flashback:   3.0 –  8.0 = 5.0s  (fixed)
  buildup:     8.0 – drop_time   = variable (minimum 4.0s)
  escalation:  drop_time – 30.0  = variable (at least 4.0s)
If drop_time < 8.0, clamp buildup start to 8.0 (so phase 2 stays intact) and let escalation
absorb the remaining time.

MATCH CUTS (Bewegungsschnitt):
The analysis data field "clip_scenes" maps each clip filename to {"tags", "scenes"} where "scenes"
are short per-frame descriptions. USE these descriptions to find pairs of clips with similar motion.
Find SIMILAR MOVEMENTS across different scenes and cut IN THE MIDDLE OF THE MOTION:
- Adjusting glasses/hat outdoors → hand reaching for the XONE mixer or CDJs in the club
- Walking forward on the street → leaning forward over the decks
- Arm gesture in daylight → arm raised in the crowd
- Turning head outdoors → turning to look at the crowd
Use 1–3 match cuts per reel, preferably at phase boundaries (flashback→buildup, buildup→escalation).
Set "transition": "match_cut" and describe the movement connection in "reason".

COLOR RULES:
- "flashback" + "buildup" clips → LUT: "tech_noir" (cold, industrial, near‑monochrome).
- "hook" + "escalation" clips (club) → LUT: "underground_dark" or "neon_nights".
HARD CUTS ONLY. No crossfades. The aesthetic is brutalist and abrupt.
"""



_ARTIST_NARRATIVE_SECTION = """
ARTIST-NARRATIVE / STORY-WEAPON MODE (preset = artist_narrative) — OVERRIDES the generic rules.
Goal: REACH. Turn the gig's backstory (train ride, walking, crew moments) into a story with a sharp,
often sarcastic or "deep" take on DJ life. The viewer should feel they are on a MISSION with you.
Retention pipeline: bait in 3s → make them feel the grind → pay it off with the drop.

ANTI-ADVICE / "POV" HOOK (REQUIRED — put it in the top-level "hook_text" field):
ONE punchy on-screen line for the first 3s, sarcastic/deep, contrasting the grind with the reward.
Under ~70 chars, no hashtags/emojis. Match this energy (do NOT copy verbatim):
  - "POV: 6h Zugfahrt für ein 90-Minuten-Set im roten Bereich."
  - "niemand sieht die 8 Stunden vorher. nur die 8 Sekunden danach."
  - "the train was late. the drop wasn't."

PHASES (set each clip's "phase"):
1. "hook" (0–3s): the text hook over a grabbing image — can be a quiet/tense travel shot OR a flash of
   the club to come. Establish the contrast immediately.
2. "journey" (3s → drop): the grind, CHRONOLOGICAL — train, walking, van, soundcheck, crew (ARRIVAL /
   BACKSTAGE / outdoor). DESATURATED, mechanical, cold. LUT: "tech_noir". Cuts on the beat but the
   muffled bass (J-cut) rumbles underneath. Energy deliberately suppressed.
3. "escalation" (drop → end): EXPLODE into the club exactly at music drop_times[0].time. Strobes, crowd,
   decks, full energy (CROWD_ENERGY / LIGHT_SHOW). LUT: "underground_dark" / "neon_nights".
The LAST "journey" clip before the club → VFX: "glitch". VFX: "flash" on the hardest club hit.
HARD CUTS. The contrast quiet→explosion is the whole point.
"""

_BOOKING_SECTION = """
BOOKING / PROMOTER-SHOWCASE MODE (preset = booking) — OVERRIDES the generic rules.
This is a DIGITAL BUSINESS CARD for club owners / promoters. In 10 seconds they must see: this artist is
professional, the floor is PACKED, the energy fits. NO private moments, NO funny train scenes, NO journey.
Pure, uncompromising professionalism and escalation.

RULES:
- Content ONLY: technique at the mixer (hands on XONE / Pioneer / CDJs, DJ_SETUP) intercut with WIDE shots
  of the packed, celebrating crowd (CROWD_ENERGY / LIGHT_SHOW). EXCLUDE ARRIVAL / BACKSTAGE / outdoor /
  travel / goofing-around clips entirely.
- FRONT-LOAD the single most impressive crowd/energy moment in the first 3s (retention) — no slow intro.
- Fast, precise, confident cuts on kicks/snares. Tight, never sloppy. Keep energy HIGH the whole time,
  no comedown. If music_analysis exists, peak the cut frequency around drop_times[0].time.
- LUT: "underground_dark" or "neon_nights" (club look only — NEVER "tech_noir", there is no journey).
- VFX: "flash" / "pump" on hits. No "glitch" (that signals a scene change; here it's all one world).
- "hook_text" stays "" — this sells through pure visual professionalism, not a text gimmick.
Set each clip's "phase": "opener" | "showcase" | "peak".
"""

_COMMUNITY_SECTION = """
COMMUNITY / BEHIND-THE-SCENES MODE (preset = community) — OVERRIDES the generic rules.
For the existing fanbase: the jokes on the train, messing around with the crew, the unfiltered reality
before and after the gig. Build a real, approachable bond. Show the contrast between "private Patrick"
and the "unapproachable machine DAY SHØ" behind the decks.

RULES:
- USE the human clips: ARRIVAL, BACKSTAGE, PACKDOWN, crew moments, candid/outdoor. The generic
  "avoid BACKSTAGE" rule does NOT apply — these ARE the content.
- CHRONOLOGICAL and looser pacing — NOT a brutalist beat-massacre. Clips may breathe (up to ~6s).
  Cuts can follow story beats, not only kicks.
- The KEY beat: at least one HARD contrast cut from a candid/goofy private moment straight into a
  focused, intense behind-the-decks shot (the "Patrick → DAY SHØ" flip). Consider VFX "glitch" there.
- Warmer, natural look: LUT "vhs_analog" for the candid/BTS moments, "underground_dark" for the booth.
- Retention: still open with the most charming/funny 3s so the fan stops scrolling.
- "hook_text" optional — a light, personal line (e.g. "die jungs vs. das set."). "" is fine.
Set each clip's "phase": "before" | "during" | "after" (chronological).
"""


def _build_system_prompt(preset: str, duration: float, target_bpm: float = 0) -> str:
    """Build the system prompt for the regie AI task."""
    sections = {
        "pov_story": _POV_STORY_SECTION,
        "tarantino": _TARANTINO_SECTION,
        "artist_narrative": _ARTIST_NARRATIVE_SECTION,
        "booking": _BOOKING_SECTION,
        "community": _COMMUNITY_SECTION,
    }
    preset_section = sections.get(preset, "")

    return f"""You are an expert video editor and creative director specializing in techno/electronic music content for Instagram Reels.

Your task: Create a precise, millisecond-accurate edit plan for a DJ video reel.

EDIT SPECIFICATIONS:
- Target duration: {duration} seconds
- Preset style: {preset}
- Target BPM: {target_bpm or "auto-detect"}
- Output format: 9:16 (1080x1920) for Instagram Reels
- Color grading: 3D-LUT underground techno look

EDITING RULES:
1. Every cut MUST land on a beat, kick, snare, or drop timestamp
2. Build dramatic tension: start calm → build up → peak at drops → cool down
3. Prioritize CROWD_ENERGY and LIGHT_SHOW tags for peak moments
4. Avoid UNUSABLE and BACKSTAGE segments
5. Use hard cuts on kicks/snares for energy, crossfades for transitions
6. Keep individual clips between 2-8 seconds (reels need fast pacing)
7. If a clip has high motion (>0.8), consider slow-motion (setpts=PTS*2.0)
8. VFX rules: Use "vfx": "flash" on the hardest drops. Use "vfx": "pump" on driving kicks. Use "vfx": "glitch" on a clip that marks a hard scene change (e.g. the cut from daytime/outdoor footage into the dark club) for a machine-like black-frame stutter. Otherwise "none".
9. The last clip should create a seamless loop feel if possible
10. The analysis JSON includes "clip_durations" (real length of each source file in seconds). NEVER set a clip's "end" beyond its source duration.
11. **Per‑clip audio analysis**: Each video in phase_2 may contain an "audio_analysis" dict with: tempo, beat_times, bass_drops, buildups, breakdowns, energy_envelope, energy_times. Use these to align cuts to that specific video's kicks/beats. If a video lacks audio_analysis, fall back to the global beat grid.
12. **Music track analysis** (optional): If present in music_analysis, it contains: bpm, kick_times, drop_times, beat_times. You may align cuts to the music track for a tighter sync between the reel and the background audio. If both per‑clip and music track data exist, prefer per‑clip data for the video's own cuts, but use music track data for the overall pacing and drop alignment.

PRESET DEFINITIONS:
- "highlight": Best moments, high energy, fast cuts, 60-90s
- "drop_focus": Centered around drops, build-up → drop → aftermath
- "seamless_loop": Short (15-30s), end flows back to start
- "moody": Slower cuts, atmospheric, BREAKDOWN + LIGHT_SHOW heavy
- "pov_story": POV / "A Day in the Life" — story-driven vlog reel (before → during → after a gig) with an anti-advice text hook in the first 3s
- "tarantino": Non-linear, brutalist techno edit — climax first (in media res), then chronological flashback (tech-noir, hard beat-cuts), buildup, escalation
- "artist_narrative": Story-weapon for reach — sarcastic/deep POV hook, desaturated grind (journey), then explode into the club at the drop
- "booking": Promoter showcase / business card — pure professionalism, mixer technique + packed crowd, no private scenes, relentless escalation
- "community": Behind-the-scenes for fans — chronological, looser, crew/candid moments, the "private Patrick vs machine DAY SHØ" contrast
{preset_section}
You MUST respond with ONLY valid JSON in this exact format (no markdown fences, no commentary):
{{
  "clips": [
    {{
      "video": "filename.mov",
      "start": 12.345,
      "end": 18.789,
      "transition": "hard_cut_on_beat",
      "reason": "Drop starts here, crowd erupts",
      "crop": "9:16",
      "lut": "underground_dark",
      "vfx": "flash",
      "slow_mo": false,
      "slow_mo_factor": 1.0,
      "phase": ""
    }}
  ],
  "narrative": "Description of the edit's story arc",
  "hook_text": ""
}}

SCHEMA NOTES:
- "phase": pov_story / community → "before" | "during" | "after"; tarantino → "hook" | "flashback" | "buildup" | "escalation"; artist_narrative → "hook" | "journey" | "escalation"; booking → "opener" | "showcase" | "peak"; "" for all other presets.
- "hook_text": REQUIRED (non-empty) for pov_story and artist_narrative; optional for community; "" otherwise."""


# ---------------------------------------------------------------------------
# JSON Response Parser (shared across all providers)
# ---------------------------------------------------------------------------

def _parse_edit_plan(raw: str, provider_name: str = "", model_id: str = "") -> EditPlan:
    """Parse AI JSON response into an EditPlan. Handles markdown fences and extra text."""
    # Strip markdown fences
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        # Remove first line (```json or ```)
        cleaned = "\n".join(lines[1:])
    if cleaned.endswith("```"):
        cleaned = cleaned[:-3]
    cleaned = cleaned.strip()

    # Try to find JSON object in the response (some providers add text before/after)
    json_start = cleaned.find("{")
    json_end = cleaned.rfind("}") + 1
    if json_start >= 0 and json_end > json_start:
        cleaned = cleaned[json_start:json_end]

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError as e:
        # LLMs occasionally emit slightly malformed JSON (missing/trailing
        # commas). Try to repair it before giving up.
        logger.warning(f"{provider_name} JSON invalid ({e}); attempting repair...")
        try:
            from json_repair import repair_json
            parsed = repair_json(cleaned, return_objects=True)
            if not isinstance(parsed, dict):
                raise ValueError("repaired JSON is not an object")
            logger.info(f"  Repaired malformed JSON from {provider_name}")
        except Exception as repair_err:
            logger.error(f"Failed to parse {provider_name} response as JSON: {e}")
            logger.debug(f"Raw response: {raw[:500]}")
            raise ValueError(f"Invalid JSON from {provider_name}: {e}") from repair_err

    clips = []
    for c in parsed.get("clips", []):
        clips.append(EditClip(
            video=c["video"],
            start=float(c["start"]),
            end=float(c["end"]),
            transition=c.get("transition", "cut"),
            reason=c.get("reason", ""),
            crop=c.get("crop", "9:16"),
            lut=c.get("lut", "underground_dark"),
            vfx=c.get("vfx", "none"),
            slow_mo=c.get("slow_mo", False),
            slow_mo_factor=c.get("slow_mo_factor", 1.0),
            phase=c.get("phase", ""),
        ))

    total = sum(c.duration for c in clips) if clips else 0

    return EditPlan(
        clips=clips,
        narrative=parsed.get("narrative", ""),
        hook_text=parsed.get("hook_text", ""),
        total_duration=total,
        style="highlight",
        provider_used=provider_name,
        model_used=model_id,
    )


# ---------------------------------------------------------------------------
# Data trimming for context limits
# ---------------------------------------------------------------------------

def _trim_analysis_for_prompt(data: dict, max_beats: int = 200) -> dict:
    """Trim large analysis data to fit within API context limits."""
    trimmed = {}

    for key, value in data.items():
        if isinstance(value, list) and len(value) > max_beats:
            half = max_beats // 2
            quarter = max_beats // 4
            trimmed[key] = value[:half] + ["..."] + value[-quarter:]
        elif isinstance(value, dict):
            trimmed[key] = value
        else:
            trimmed[key] = value

    return trimmed


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_edit_plan(
    analysis_data: dict,
    preset: str = "highlight",
    duration: float = 60.0,
    target_bpm: float = 0.0,
    provider: str = "",
    output_path: Path | None = None,
    temperature: float = 0.4,
    max_tokens: int = 8192,  # headroom for reasoning models (e.g. deepseek) whose
                             # chain-of-thought counts against the token budget
) -> EditPlan:
    """
    Generate an AI-directed edit plan.

    Args:
        analysis_data: Complete analysis dict containing:
            - audio: {bpm, beats, drops, kicks, snares, buildups}
            - video: {scenes, motion_scores, light_changes}
            - vision_tags: [{time, tag, confidence, description}]
            - highlights: [{start, end, score}]
            - sync_offsets: {filename: offset_seconds}
        preset: Edit style preset ("highlight", "drop_focus", "seamless_loop", "moody")
        duration: Target reel duration in seconds
        target_bpm: Override BPM (0 = auto-detect)
        provider: AI provider to use ("claude", "gemini", "deepseek", "" = auto)
        output_path: Optional path to save the plan JSON
        temperature: Generation temperature (0.0-1.0)
        max_tokens: Max tokens in response

    Returns:
        EditPlan with precise clip selections
    """
    # Resolve provider
    ai = resolve_provider(provider)

    logger.info(f"Generating edit plan: preset={preset}, duration={duration}s")
    logger.info(f"  Provider: {ai.name} ({ai.model_id})")

    # Build prompts
    system_prompt = _build_system_prompt(preset, duration, target_bpm)

    # Musikdaten als zusätzlichen Abschnitt im System-Prompt einfügen (für alle Presets)
    music_analysis = analysis_data.get("music_analysis")
    if music_analysis and "error" not in music_analysis:
        music_summary = "\n\nMUSIC TRACK ANALYSIS (use for timing cuts, drops, and overall pacing):\n"
        if music_analysis.get("bpm"):
            music_summary += f"- BPM: {music_analysis['bpm']:.1f}\n"
        if music_analysis.get("beat_times"):
            beats = music_analysis["beat_times"]
            music_summary += f"- {len(beats)} beat_times: first 8 = {beats[:8]}\n"
        if music_analysis.get("kick_times"):
            kicks = music_analysis["kick_times"]
            music_summary += f"- {len(kicks)} kick_times: first 10 = {kicks[:10]}\n"
        if music_analysis.get("drop_times"):
            drops = music_analysis["drop_times"]
            music_summary += f"- {len(drops)} drop_times: {drops[:5]}\n"
        if music_analysis.get("subbass_energy"):
            # Nur zeigen, dass es existiert
            music_summary += f"- subbass_energy curve available ({len(music_analysis['subbass_energy'])} values)\n"
        system_prompt += music_summary

    trimmed = _trim_analysis_for_prompt(analysis_data)
    user_data = f"ANALYSIS DATA:\n```json\n{json.dumps(trimmed, indent=2, ensure_ascii=False, default=str)}\n```"

    # Call AI provider
    t0 = time.time()
    raw_response = ai.call(
        system_prompt=system_prompt,
        user_data=user_data,
        temperature=temperature,
        max_tokens=max_tokens,
    )
    elapsed = time.time() - t0

    logger.info(f"  Response received in {elapsed:.1f}s")

    # Parse response
    plan = _parse_edit_plan(raw_response, provider_name=ai.name, model_id=ai.model_id)
    plan.generation_time_s = elapsed
    plan.style = preset  # reflect the requested preset (parser defaults to "highlight")

    # Verify and fix
    plan = verify_edit_plan(plan, analysis_data, target_duration=duration)

    if output_path:
        plan.save(output_path)

    logger.info(f"Edit plan generated: {len(plan.clips)} clips, {plan.total_duration:.1f}s total "
                f"[{ai.name}/{ai.model_id}, {elapsed:.1f}s]")
    return plan


def generate_multi_plan(
    analysis_data: dict,
    preset: str = "highlight",
    duration: float = 60.0,
    target_bpm: float = 0.0,
    providers: list[str] | None = None,
) -> dict[str, EditPlan]:
    """
    Generate edit plans from MULTIPLE providers for comparison/A/B testing.
    Each provider with a configured API key generates its own plan.

    Returns:
        Dict of {provider_name: EditPlan}
    """
    if providers is None:
        providers = REGIE_PROVIDER_FALLBACK_ORDER

    results: dict[str, EditPlan] = {}

    for provider_name in providers:
        try:
            provider = get_provider(provider_name)
            if not provider.is_available():
                logger.info(f"Skipping {provider_name}: API key not set")
                continue

            logger.info(f"\n{'=' * 40}")
            logger.info(f"Generating plan with {provider_name}...")

            plan = generate_edit_plan(
                analysis_data,
                preset=preset,
                duration=duration,
                target_bpm=target_bpm,
                provider=provider_name,
            )
            results[provider_name] = plan

        except Exception as e:
            logger.error(f"  {provider_name} failed: {e}")
            continue

    if not results:
        raise RuntimeError("All providers failed to generate edit plans")

    return results


# ---------------------------------------------------------------------------
# Verification & Self-Healing
# ---------------------------------------------------------------------------

def _source_duration(video_path: str, _cache: dict = {}) -> float:
    """Source media duration via ffprobe, cached per path. 0.0 if unknown."""
    if video_path in _cache:
        return _cache[video_path]
    import subprocess
    try:
        out = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "csv=p=0", video_path],
            capture_output=True, text=True, timeout=30,
        )
        dur = float(out.stdout.strip()) if out.returncode == 0 else 0.0
    except Exception:
        dur = 0.0
    _cache[video_path] = dur
    return dur


def verify_edit_plan(
    plan: EditPlan,
    analysis_data: dict,
    target_duration: float = 60.0,
) -> EditPlan:
    """
    Verify an edit plan and fix common issues:
    - Clips with zero/negative duration
    - Overly long clips (>15s)
    - End times beyond the real source duration (AI overshoot) – clamped,
      then the lost time is recovered by extending clips that have headroom
    - Duration mismatch warnings
    """
    if not plan.clips:
        logger.warning("Empty edit plan - nothing to verify")
        return plan

    fixed_clips = []
    for clip in plan.clips:
        if clip.end <= clip.start:
            logger.warning(f"Skipping zero/negative duration clip: {clip.video} [{clip.start}-{clip.end}]")
            continue

        # Clamp against the REAL source duration – the AI only sees analysis
        # data and routinely plans end times past the end of short clips.
        src_dur = _source_duration(clip.video)
        if src_dur > 0:
            if clip.start >= src_dur:
                logger.warning(
                    f"Skipping clip starting past source end: {clip.video} "
                    f"[start={clip.start:.1f}s, source={src_dur:.1f}s]"
                )
                continue
            if clip.end > src_dur:
                logger.warning(
                    f"Clamping clip end to source duration: {clip.video} "
                    f"[{clip.end:.1f}s → {src_dur:.1f}s]"
                )
                clip.end = src_dur

        clip_duration = clip.duration
        if clip_duration > 15.0:
            logger.warning(f"Trimming long clip ({clip_duration:.1f}s): {clip.video}")
            clip.end = clip.start + 15.0

        fixed_clips.append(clip)

    plan.clips = fixed_clips
    plan.total_duration = sum(c.duration for c in plan.clips)

    # Recover clamped time: extend clips whose SOURCE has headroom past their
    # planned end. Start times stay untouched (they are beat-aligned cut-ins);
    # shots just breathe a little longer. Max +2 s per clip, 15 s clip cap.
    shortfall = target_duration - plan.total_duration
    if shortfall > 1.0:
        for clip in plan.clips:
            if shortfall <= 0:
                break
            src_dur = _source_duration(clip.video)
            if src_dur <= 0:
                continue
            headroom = min(src_dur - clip.end, 2.0, 15.0 - clip.duration)
            if headroom > 0.1:
                extend = min(headroom, shortfall)
                clip.end = round(clip.end + extend, 3)
                shortfall -= extend
        recovered = sum(c.duration for c in plan.clips) - plan.total_duration
        if recovered > 0.05:
            logger.info(f"Recovered {recovered:.1f}s by extending clips with source headroom")
        plan.total_duration = sum(c.duration for c in plan.clips)

    duration_diff = abs(plan.total_duration - target_duration)
    if duration_diff > 5.0:
        logger.warning(
            f"Duration mismatch: plan={plan.total_duration:.1f}s vs target={target_duration:.1f}s "
            f"(diff={duration_diff:.1f}s)"
        )

    logger.info(
        f"Verification: {len(plan.clips)} clips, "
        f"total={plan.total_duration:.1f}s, "
        f"target={target_duration:.1f}s"
    )

    return plan


# ---------------------------------------------------------------------------
# Seamless Loop Helper
# ---------------------------------------------------------------------------

def create_seamless_loop_plan(
    video_path: str,
    start: float,
    end: float,
    crossfade_duration: float = 0.5,
) -> EditPlan:
    """
    Create a seamless loop edit plan by splitting a clip and swapping halves.
    End-clip goes first, Start-clip goes last, with crossfade at the junction.
    Exploits Instagram's loop behavior for higher view counts.
    """
    midpoint = (start + end) / 2

    return EditPlan(
        clips=[
            EditClip(
                video=video_path,
                start=midpoint,
                end=end,
                transition="crossfade",
                reason="Second half of original (plays first for seamless loop)",
            ),
            EditClip(
                video=video_path,
                start=start,
                end=midpoint,
                transition="crossfade",
                reason="First half of original (plays second for seamless loop)",
            ),
        ],
        narrative="Seamless loop: end flows back to start for infinite replay",
        total_duration=end - start,
        style="seamless_loop",
        provider_used="algorithmic",
        model_used="seamless_loop_v1",
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    import sys

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")

    parser = argparse.ArgumentParser(
        description="UNREEL V3 – Regie Engine (Multi-Provider AI)",
    )
    parser.add_argument("analysis_json", help="Path to analysis JSON file")
    parser.add_argument("--preset", "-p", default="highlight",
                        choices=["highlight", "drop_focus", "seamless_loop", "moody", "pov_story", "tarantino", "artist_narrative", "booking", "community"])
    parser.add_argument("--duration", "-d", type=float, default=60.0)
    parser.add_argument("--provider", choices=["claude", "gemini", "deepseek", "auto"],
                        default="auto", help="AI provider (default: auto)")
    parser.add_argument("--multi", action="store_true",
                        help="Generate plans from ALL available providers for comparison")
    parser.add_argument("--output", "-o", type=Path, default=Path("output/edit_plan.json"))
    parser.add_argument("--verbose", "-v", action="store_true")

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    with open(args.analysis_json) as f:
        analysis = json.load(f)

    # Show provider status
    print("\n📡 Provider Status:")
    for p in list_available_providers():
        status = "✅ available" if p["available"] else "❌ no API key"
        print(f"  {p['name']:10s}  {p['model']:25s}  {status}")
    print()

    if args.multi:
        # Multi-provider comparison
        results = generate_multi_plan(analysis, preset=args.preset, duration=args.duration)

        print(f"\n{'=' * 60}")
        print(f"MULTI-PROVIDER COMPARISON ({len(results)} plans)")
        print(f"{'=' * 60}")

        for name, plan in results.items():
            print(f"\n  [{name.upper()}] {plan.model_used}")
            print(f"  Clips: {len(plan.clips)}, Duration: {plan.total_duration:.1f}s, "
                  f"Time: {plan.generation_time_s:.1f}s")
            print(f"  Narrative: {plan.narrative}")
            plan.save(args.output.parent / f"edit_plan_{name}.json")

    else:
        # Single provider
        plan = generate_edit_plan(
            analysis,
            preset=args.preset,
            duration=args.duration,
            provider=args.provider,
            output_path=args.output,
        )

        print(f"\nEdit Plan by {plan.provider_used} ({plan.model_used})")
        print(f"  {len(plan.clips)} clips, {plan.total_duration:.1f}s, generated in {plan.generation_time_s:.1f}s")
        print(f"  Narrative: {plan.narrative}\n")

        for i, clip in enumerate(plan.clips):
            print(f"  [{i + 1:02d}] {Path(clip.video).name:30s}  "
                  f"{clip.start:7.3f}s → {clip.end:7.3f}s  "
                  f"({clip.duration:.1f}s)  {clip.transition}")

        print(f"\nSaved to {args.output}")
